ALTER TABLE "Reminders" ADD COLUMN IF NOT EXISTS "user_id" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid;
ALTER TABLE "Reminders" ALTER COLUMN "user_id" DROP DEFAULT;
ALTER TABLE "Reminders" ADD COLUMN IF NOT EXISTS "is_sent" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Reminders" ADD CONSTRAINT "Reminders_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
